image: maven:3.6.0-jdk-11-slim
pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B initialize verify    # -B batch mode makes Maven less verbose
        services: 
          - postgres 

definitions: 
  services: 
    postgres: 
      image: postgres
      environment:
        POSTGRES_DB: atomic
        POSTGRES_USER: atomic
        POSTGRES_PASSWORD: atomic
